# Generated by Django 4.2.7 on 2023-11-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nerd',
            name='sobre',
            field=models.TextField(default='Resumo do Filme', max_length=900),
        ),
    ]
